### ISSUE TITLE
Does magpie work with spark?

### ISSUE THREAD

**Issue by iymitchell** [inspirehep/magpie#101]
I am trying to use this module with a spark cluster since I am working on a large amount of data.  Does magpie support it or deep inside the code could it be used with a spark cluster?  Any help would be appreciated.

**Comment by jstypka** [comment]
Not as far as I have seen unfortunately. There are some attempts to run Keras or TensorFlow on Spark (like [here](https://github.com/maxpumperla/elephas) or [here](https://github.com/cerndb/dist-keras)), so in theory it's probably possible to run also Magpie on top, but I don't know of any attempts to do that. You can be the first :)
