### ISSUE TITLE
Magpie import error

### ISSUE THREAD

**Issue by rpatra** [inspirehep/magpie#107]
Hello,
I am trying use magpie for multi-class text classification.
For the first few times, it works fine, then I get this error after waiting for 4-5 mins: https://gist.github.com/rpatra/973f14db88b50e6dd52713e5a4c87037

After I uninstall and then reinstall it, it works again for few times.
Any suggestions to fix this issue?

Thanks

**Comment by jstypka** [comment]
that looks weird. NLTK (Magpie's dependency used for language processing) seem to have a problem loading one of the tokenizers. If you say that it works fine previously, I assume that the library is downloaded and stored successfully, but then fails to load somehow? I think you'd be better off asking some folks at [NLTK](https://github.com/nltk/nltk) that know much more about it then me.
