### ISSUE TITLE
Keras model save error

### ISSUE THREAD

**Issue by rpatra** [inspirehep/magpie#108]
Hello,
I get another error while saving the magpie model
magpie.save_word2vec_model and magpie.save_scaler works fine but magpie.save_model gives the following error:

File "magpie/main.py", line 270, in save_model
    self.keras_model.save(filepath)
AttributeError: 'NoneType' object has no attribute 'save'

So, it might be some issue related to Keras possibly. Any suggestions?

Another question, is there some way to set the number of workers for word2vec model? In the code, I  see that its set to 4 always.

**Comment by jstypka** [comment]
You seem to be trying to save the model before training it. The object is initialized with `keras_model=None` which is then overwritten when functions like `train` or `batch_train` are called. If you save the model before calling one of them, the error will go off. Another point being that Magpie should probably check for None itself and print a reasonable error message, I should fix that.

And for the other question - currently there's no way to do it unfortunately. I'll try to add it to the `config.yaml` when I have a minute
