### ISSUE TITLE
could I import magpie in window platform

### ISSUE THREAD

**Issue by xiaochao00** [inspirehep/magpie#114]
Hi, when I run "pip install magpie" get error. I see somewhere magpie can run in window by cywgwin, but this is not resolve the problem run in window platform.
`Collecting sh==1.09 (from magpie)
  Using cached sh-1.09.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\13631\AppData\Local\Temp\pip-build-xek982wm\sh\setup.py", line 4, in <module>
        import sh
      File "C:\Users\13631\AppData\Local\Temp\pip-build-xek982wm\sh\sh.py", line 34, in <module>
        support." % __version__)
    ImportError: sh 1.09 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.`

could I get help from you , thanks

**Comment by jstypka** [comment]
hey, you're installing a different library - this `magpie` is not in PyPI. Run `pip install git+https://github.com/inspirehep/magpie.git@v2.0` instead.
