### ISSUE TITLE
Since Python3 reduce has been moved to the functools package

### ISSUE THREAD

**Issue by NowayIndustries** [inspirehep/magpie#116]
As per the title, ever since Python3 reduce is now part of the functools package.

This is an issue when you want to use [`train_word2vec_in_memory`](https://github.com/inspirehep/magpie/blob/master/magpie/base/word2vec.py#L14) as suggested in #105, lucky for us it is easily fixed.

Simply add an `from functools import reduce` to [word2vec.py](https://github.com/inspirehep/magpie/blob/master/magpie/base/word2vec.py#L5), [this fix is even compatible with Python2.7](https://docs.python.org/2.7/library/functools.html#functools.reduce)

I've created a pull request containing this fix, see #115.

**Comment by jstypka** [comment]
Good catch, thanks for the PR!
