### ISSUE TITLE
What is the CNN model behind Magpie?

### ISSUE THREAD

**Issue by datduong** [inspirehep/magpie#135]
Hi, I would like to know at a high level detail, what is the CNN model behind Magpie? 

Does Magpie use the model by Kim, Yoon. "Convolutional neural networks for sentence classification." ?

I am planning to use Magpie as a baseline for my experiment, so I would need this information. Thanks.

**Comment by jstypka** [comment]
hey @datduong! Yes, that's exactly the one.

**Comment by datduong** [comment]
Thank you.
