### ISSUE TITLE
Request/Queries  - Not a Issue :  Building Word2Vec Model and use that in Python

### ISSUE THREAD

**Issue by rajeshkumargp** [inspirehep/magpie#139]
Hi Magpie Team, 
I have below queries . 
1. I am trying to build Word2Vec in C, 
  Can i use it Magpie since it is python based . If so, how can i load the vector from C's binary to Python's magpie Word2Vec object 
2. Can I build using fasttext and use that in Magpie .. 

 Please provide suggestions on this.

**Comment by jstypka** [comment]
hey @rajeshkumargp,

We use [gensim object](https://radimrehurek.com/gensim/models/word2vec.html) for word2vec, which uses C under the hood to compute the vectors. If you manage to convert your vectors to this object, then Magpie will support it.

In principle, you can pass whatever as the word2vec object that can behave like a dictionary. You could build your vectors any way you want, you just need to pass them in inside a dictionary-like data structure that would conform to [this code](https://github.com/inspirehep/magpie/blob/master/magpie/nn/input_data.py#L76-L77) and it should fly. Watch out to get the vector dimensions right though! 

Best!

**Comment by rajeshkumargp** [comment]
Thanks @jstypka , I have tried It is performing well
