### ISSUE TITLE
Testing the model on a single batch of samples

### ISSUE THREAD

**Issue by anoumaru** [inspirehep/magpie#143]
I built a model and everything seems to be working fine but now I want to evaluate the performance of the model, I searched in the keras documentation and I've found the function **test_on_batch**(self, x, y, sample_weight=None). I don't know how I can use it in the magpie ?

**Comment by anoumaru** [comment]
Thanks Jan for replying so fast. I managed to get the data with the **get_data_for_model** function, but now trying to evaluate the model with model.test_on_batch(x, y) I get this error : ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 5 array(s), but instead got the following list of 1 arrays: 

Here is how I proceeded:

import gensim
from keras.models import load_model
from sklearn.externals import joblib 

#loading keras model 

model = load_model('PathTo/model.h5')

#loading word2vec model 

word2vec_model = gensim.models.Word2Vec.load("PathTo/wordVecModel")

#loading scaler model 

scaler = joblib.load('PathTo/scaler') 



(x, y), test_data = get_data_for_model('PathTo',labels,test_dir ='PathTo',word2vec_model=word2vec_model,scaler=scaler)



>>>scaler
StandardScaler(copy=False, with_mean=True, with_std=True)

>>>model
<keras.engine.training.Model object at 0x000001FB44286AC8>

>>>word2vec_model
Word2Vec(vocab=1612, size=100, alpha=0.025)


>>> print(x)
[array([[[ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [-0.21557015,  1.6357888 ,  0.74245095, ..., -0.01091613,
          0.35933   ,  0.20148979],
        [ 0.09036439,  2.47400761,  0.68469423, ..., -0.25815552,
          1.34764314, -0.41480115],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]],

       [[ 3.48997188, -2.57695794, -3.65844631, ..., -3.69014978,
          3.38401747, -3.44170642],
        [-0.03670162,  0.16872324,  0.20004952, ...,  0.25931892,
         -0.12368937,  0.33218005],
        [-0.14250578,  1.79165494,  0.79259813, ...,  0.1169867 ,
          0.95397741,  0.38188335],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]],

       [[ 0.09286351,  0.72259045,  0.41380054, ..., -0.01159158,
          0.53722638, -0.01254273],
        [-0.66032797,  0.19171472,  0.61856663, ...,  0.44296047,
         -0.41840297,  0.9109301 ],
        [-0.3719466 , -0.18901879,  0.31801546, ...,  0.46948984,
         -0.40740594,  0.23664768],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]],

       ...,
       [[-0.27928856, -0.07504759,  0.24097225, ...,  0.33535874,
         -0.23131363,  0.55473012],
        [ 0.39277405,  0.76646304, -0.40170971, ..., -0.10361902,
          0.54636383, -0.51476246],
        [ 0.15314823, -0.05881924, -0.03674226, ..., -0.03152359,
         -0.24654508, -0.18140598],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]],

       [[ 0.0169089 ,  0.69833708,  0.3733184 , ..., -0.1293356 ,
          0.55406612, -0.22023457],
        [ 0.09286351,  0.72259045,  0.41380054, ..., -0.01159158,
          0.53722638, -0.01254273],
        [ 0.27658051,  0.4611814 ,  0.05094949, ..., -0.07105287,
          0.44061378, -0.19075936],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.07211996, -0.73211867, -0.4157961 , ..., -0.16305456,
          0.16197838, -0.43225273],
        [ 0.10721994,  0.38397825,  0.05596666, ...,  0.12396832,
         -0.013932  ,  0.05911507],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]]])]

		  
>>>model.test_on_batch(x,y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\t712\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\training.py", line 1918, in test_on_batch
    sample_weight=sample_weight)
  File "C:\Users\t712\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\training.py", line 1476, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\t712\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\training.py", line 86, in _standardize_input_data
    str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 5 array(s), but instead got the following list of 1 arrays: [array([[[ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [-0.21557015,  1.6357888 ,  0.74245095, ..., -0.01091613,
          0.35933   ,  0.201489...

How can I make the numpy array with this size ?

**Comment by jstypka** [comment]
could you print the shape of the arrays? [`x.shape`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html) should do. If x is a normal list, you can try to get `len(x)` and then `x[0].shape` for instance.

You can also try to switch `cnn` to `rnn` in the [`config.py`](https://github.com/inspirehep/magpie/blob/master/magpie/config.py#L10), that might fix it (you'll need to retrain the model though and it's gonna be muuuuch slower).

**Comment by anoumaru** [comment]
I'll be print that on monday when I'm in the office. 

have a nice Weekend !

**Comment by anoumaru** [comment]
Here are the print results : 

>>> len(x)
1
>>> x[0].shape
(2091, 200, 100)
>>> len(y)
2091
>>> y[0].shape
(27,)

Unfortunately, I need to use convolutional neural networks, so that's not an option.
