### ISSUE TITLE
The point of using the scaler

### ISSUE THREAD

**Issue by aburkov** [inspirehep/magpie#147]
Hi! What exactly the point of using the scaler? I checked the two articles (Kim and Berger), they don't give any detail about the need for a scaler.

Whether the only purpose of using the scaler it's a heuristics that prescribes to transform all input data dimensions to have the mean of 0 and the standard deviation of 1 for better results?

Also, what should be the input dataset for the scaler? Should that be the same dataset I used to build word vectors or it has to be the labeled dataset I will use to train the classifier?

Thanks!

**Comment by jstypka** [comment]
hey @aburkov . The point of the scaler is, as you say, to make sure that all the features have a 0 mean and a unit standard deviation. Not ensuring that might cause some of the features (vector dimensions in our case) to overpower others and make it more difficult to the network to learn.

Now in practice, it doesn't matter that much. The word2vec model ensures that the dimensions are _more or less_ in the same range and even if there's a bias, the network should be able to learn it anyway. So the scaler's role is mostly to speed up the learning process by normalizing the dimensions. I run it a couple of times without the scaler and the final accuracy was the same, but it took a little bit longer to converge.

Hope that helps!
