### ISSUE TITLE
How magpie uses title and text

### ISSUE THREAD

**Issue by aburkov** [inspirehep/magpie#148]
Hi! In the training data examples, in *.txt files, there are two lines: the title and the abstract. How does Magpie deals with these two lines? Does it simply concatenate them together? I'm asking because at the prediction time the method "predict_from_text" only takes one parameter, so I suppose that the title is not used somehow differently from the abstract, right?

**Comment by jstypka** [comment]
@aburkov yes yes, they're just concatenated together. Adding a new line is treated as an end of sentence.
