### ISSUE TITLE
How to use this for multi label?

### ISSUE THREAD

**Issue by somnathrakshit** [inspirehep/magpie#150]
Is is possible to use this in case of multiple labels present in the same document? If yes, please point out how.

**Comment by jstypka** [comment]
yes, that's the main use case. Look at the example data, each document has more than one label assigned to it.

**Comment by somnathrakshit** [comment]
I saw a few .lab files in the data folder. All of there m had 1 label. Can you send me a link to the files that you are mentioning.

**Comment by jstypka** [comment]
Well, there's thousands of files - I'm not going to browse through them looking for examples ;) You can write a script to find files that have more than one line if you need to see one. Or you can trust me that they exist :-)

**Comment by somnathrakshit** [comment]
No, that's not what I meant. Sorry if it sounded otherwise. My question was how to store the labels in the .lab file in case of multiple labels. From your earlier comment, I understood the way out to be placing them in separate lines. That is all that I needed.

**Comment by jstypka** [comment]
That's exactly the case!
