### ISSUE TITLE
Input parameters

### ISSUE THREAD

**Issue by bigredbug47** [inspirehep/magpie#156]
Hi all,
Magpie is a wonderful tool, but what about the input parameters when using function, like changes batch size when training or changes embedding size in word2vector.
I found something in config.py file 
```
# word2vec & scaler
EMBEDDING_SIZE = 100

# Cores to use while fitting word2vec vectors
WORD2VEC_WORKERS = 4
MIN_WORD_COUNT = 5
WORD2VEC_CONTEXT = 5

# Models
NN_ARCHITECTURE = 'cnn'

# Training parameters
BATCH_SIZE = 64
EPOCHS = 1

# Number of tokens to save from the abstract, zero padded
SAMPLE_LENGTH = 200
```
That means if I change something in here it will affect to the magpie function right?
But is there a way that I can pass all necessary parameters directly to magpie function?
Thks.

**Comment by jstypka** [comment]
@bigredbug47 you can pass some of those parameters directly to the function, check the function definitions `[here](https://github.com/inspirehep/magpie/blob/master/magpie/main.py#L110-L112)`. These will overwrite the ones in the file. The rest can be edited in the configuration file.

Does that answer your question?

**Comment by bigredbug47** [comment]
Thanks, I will take a look at it.
