### ISSUE TITLE
Looks no_of_keywords is not specified/defined in utils.py 

### ISSUE THREAD

**Issue by rajeshkumargp** [inspirehep/magpie#159]
I have a query in 'no_of_keywords' 

https://github.com/inspirehep/magpie/blob/master/magpie/utils.py#L147

Looks 'no_of_keywords' is not initialized anywhere in the module. 

Please let me know if i am wrong.

**Comment by jstypka** [comment]
@rajeshkumargp you're not wrong, it's a bug. It seems like it should be no_of_labels instead no_of_keywords, we had to miss it during refactoring and the function is not used for training or testing, so it's difficult to spot. I'll try to fix it 😉

**Comment by rajeshkumargp** [comment]
Fixed the bug
