### ISSUE TITLE
Request Not a Issue Multi Label Image Classification

### ISSUE THREAD

**Issue by rajeshkumargp** [inspirehep/magpie#164]
Can we use Magpie for Multi Label Image Classification, 
ie . Input is an image 
and output is Text labels for the image.   

How to feed  images as input  in Magpie .. 
Suggestions please

**Comment by jstypka** [comment]
@rajeshkumargp in theory yes, the neural network should work for images as well, however you would have to rewrite a large part of the logic that reads and serialises the data. Also remove the word2vec embedding part and the scaling. So it's definitely possible, but you need to be able to understand well and substantially modify the code to do it.
