### ISSUE TITLE
Need Info on Scaler Fitting - issue on training by using pretrained Word2Vec and Scaler Fitted Vocabulory

### ISSUE THREAD

**Issue by rajeshkumargp** [inspirehep/magpie#168]
I have built Word2Vec model over entire Corpus. 

The Scaler fiting is being done over Current Trainng Corpus(a subset of entire corpus).Again, If I need to run training  with different set of training Corpus,  but with same Word2Vec, again Scaler fitting needs to be done. 

How can I avoid this? 
ie 
Can I make Scaler fitting too a One Time Activity similar to Word2Vec building  by genrating Scaler fitting over entire Corpus?

**Comment by jstypka** [comment]
@rajeshkumargp yeah, you can do it only once. Just run the `init_word_vectors()` function on the entire corpus to build vectors and fit the scaler and save them somewhere afterwords. Then you can reuse it every time you need to scale things.

**Comment by rajeshkumargp** [comment]
I have built Word2Vec model over entire Corpus. 
The Scaler fitting is being done over Current Trainng Corpus(a subset of entire corpus).
I have used the above Scaler Fitting and Word2Vec model for training. 

While training , i get error as below: 
_______________________________________________________________
`Fitted to 67612 vectors`
`Traceback (most recent call last):`
`  File "S005_TT_010_magpiedemo.py", line 115, in <module>`
`    magpie.train(train_dir,labels,test_ratio=0.25,epochs=1)`
`  File "/home/Abc/magpieCNN/magpie/main.py", line 96, in train`
`    scaler=self.scaler,`
`  File "/home/Abc/magpieCNN/magpie/nn/input_data.py", line 44, in get_data_for_model`
`    train_data = build_x_and_y(train_files, train_dir, **kwargs)`
`  File "/home/Abc/magpieCNN/magpie/nn/input_data.py", line 88, in build_x_and_y`
`    y_matrix[doc_id][index] = True`
`IndexError: index 1433 is out of bounds for axis 0 with size 1102`

_______________________________________________________________

Can you please guide me where I am mistaking.. 
Where am i wrong .. 

For Scaler fitting, I am using the Script at the location : 
https://github.com/rajeshkumargp/magpie/blob/master/ScalerFitting.py
 (The input is a single file containing the entire corpus which i have used for Word2Vec building)

**Comment by rajeshkumargp** [comment]
As per #171 , Due to duplicates in Labels, the above issue arose.

**Comment by jstypka** [comment]
👍
