### ISSUE TITLE
How to create a server service

### ISSUE THREAD

**Issue by pdc-kaminaga** [inspirehep/magpie#176]
I want to create a server service.
Do you have a simple examples ?

**Comment by jstypka** [comment]
Long time ago we embedded it in Flask, but it's an outdated version of Magpie. It might give you some inspiration though: https://github.com/inspirehep/inspire-magpie . Good luck!

**Comment by pdc-kaminaga** [comment]
Thank you for your reply.
I’d like to use your document as a reference.

**Comment by pdc-kaminaga** [comment]
I updated inspire-magpie and was able to use magpie v2.
Thank you very much.
