### ISSUE TITLE
Train in another language

### ISSUE THREAD

**Issue by bigredbug47** [inspirehep/magpie#189]
Hi guys,

Very interesting library. But how to train in it another language such as Japanese?

I try to train from Japanese text but it return the wrong prediction (same prediction for all records).

Thank you.

**Comment by bigredbug47** [comment]
[UPDATED]
I found that the framework use nltk to tokenize word so it only apply for english. So I have changed some script in magpie folder library that will split sentence Japanese to sentences and separated words. 
I have split from Japanese sentence to words and feed them into gensim but still didn't change anything. 
Do you have any ideas for my case?
Thank you

**Comment by jstypka** [comment]
hey @bigredbug47, interesting question! If it is not working for you, I would suspect the word2vec library might be failing to train on Japanese corpus. I don't know much about Japanese, but word2vec might e.g. rely on spaces between words or something of that sort which might not work great for Japanese.

What I'd recommend you to do is to test out purely the vector space and how it works for you. We're using gensim as the library to compute the vectors and it has an API to find synonyms and antonyms through the vector space. [Here's the link to the api.](https://radimrehurek.com/gensim/models/word2vec.html) Try it out and see whether the synonyms and antonyms make sense. If yes, then something is broken on the NN side.

**Comment by bigredbug47** [comment]
Thank you.
I think I have figured it out. Based the original framework, one sentence in and list of words of this sentence out - which will use for training the model.
And based on your code, you didn’t remove any stop words except string punctuation.
So I apply that for Japanese too, using regex to split sentences, and break sentence to words. And keep the correct output format like your read_sentences function output and feed it to model for training. The result training and testing seem reliable. I will run with more data to check the accuracy.
I will try your suggestion to learn more about the framework.
Again, Thank you a lot.
