### ISSUE TITLE
Predict journals

### ISSUE THREAD

**Issue by jstypka** [inspirehep/magpie#53]

**Comment by kaplun** [comment]
What is this idea about?
From which data do you plan to predict journals? Note that typically we do have the journal title to start with, although depending on the source of information this string needs to be normalized before it matches an existing journal entry in the journals collection

**Comment by jstypka** [comment]
It's a wild idea we had with Eamonn today to use the system we have to predict journal labels instead of keywords and subject categories that we do right now. We could train it on our corpus (with the normalization if necessary) and deploy a small webservice at CERN for people. It's like a side project though :)

**Comment by kaplun** [comment]
What exactly do you mean by journal labels? Just to fully understand :)

**Comment by jstypka** [comment]
The names of the journals - in any form that we decide on. Basically a user would be able to type in his abstract and we can advise him which journals would be appropriate for his work.

**Comment by kaplun** [comment]
:open_mouth:

**Comment by kaplun** [comment]
My wife tells me that they write abstracts depending on the journal to which they want to submit (e.g. they write abstract in PRL style if needed to submit to PRL), and they submit to a given journal depending on the impact factor... sad but true... On the other hand the project sounds funny. Maybe it can help the physicist to cross check that the journal would be compatible in style.

**Comment by jstypka** [comment]
Yeah, it was just an idea, because we could easily do it using the software we have now. Maybe it could be useful for somebody :) We could also do it for other domains, not only HEP. But not sure if we'll have time for that :)
