### ISSUE TITLE
add documentation, model loading errors

### ISSUE THREAD

**Issue by naldir** [inspirehep/magpie#70]
I have a problem with trained model loading.
Should I use the utils.load_from_disk() method alone
Should I wrap it in MagpieModel constructor ?
Both methods work but the prediction methods of the model give errors.

in any case adding more detailed documentation about model loading among others would be helpful.

**Comment by jstypka** [comment]
You should use the `MagpieModel` constructor for this and pass the trained model as `keras_model` kwargs. Remember that for prediction, Magpie also needs a word2vec model and a scaler - all of them compatible with each other, without that it will predict gibberish.

The best way to do it is to train a model and serialize all three objects separately and pass them through the constructor every time you create a `MagpieModel`. You can also create a fully fledged `MagpieModel` object and just serialize it with pickle - never tried it, but it should work as well :)

**Comment by naldir** [comment]
I feel like a newbie asking dumb questions.
I tried `magpie.utils.save_to_disk()` on the global `MagpieModel` and loaded it with `magpie.utils.load_from_disk()` then call `magpie.MagpieModel(model)`
I also tried to save and keras_model, word2vec_model, scaler and labels separately again with the magpie.utils functions then `magpie.MagpieModel(keras_model, word2vec_model, scaler, labels)`
All these gave me errors when I called `predict_from_text()`

**Comment by jstypka** [comment]
Could you paste the errors that you have? The second method should work. For the first one:
`save_to_disk('/path/file', magpie_model_obj)` should be followed by `magpie_model_obj = load_from_disk('/path/file')`. Those functions are only wrappers around the python pickle functions.

**Comment by naldir** [comment]
`MissingInputError: ("An input of the graph, used to compute DimShuffle{x,x,x}(keras_learning_phase), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.", keras_learning_phase)`

I attached the full stacktrace.

[error.txt](https://github.com/inspirehep/magpie/files/407403/error.txt)

**Comment by jstypka** [comment]
Seems like a problem with `keras`. I didn't test it beyond 1.0.2 version and it changes quite rapidly. Which version are you using and does the error also occur for `1.0.2`?

**Comment by naldir** [comment]
I was on `1.0.6` installed with pip

I installed `1.0.2`. There is an import error for which I found no solution by myself.

```
/usr/local/lib/python2.7/dist-packages/magpie/utils.pyc in load_from_disk(path_to_disk)
     26         raise ValueError("File " + path_to_disk + " does not exist")
     27 
---> 28     return pickle.load(open(path_to_disk, 'rb'))
     29 
     30 

ImportError: No module named pooling 
```

**Comment by jstypka** [comment]
are you loading a model in keras `1.0.2` that was trained with keras `1.0.6`? This might be a cause for import errors, because pickle expects the libraries to be exactly the same while saving/loading. Try to train a model with `1.0.2` and then load it.

**Comment by naldir** [comment]
the error above was certainly a `1.0.6` model loaded on `1.0.2`.
Now that I'm sure of the keras version and the model version saved the first error reappeared.

**Comment by jstypka** [comment]
It might also be a Theano issue. Did you try to predict before serializing the model? That could tell us whether it's the problem with serialization or the predicting itself. I also tested the program either Theano (0.8.2) or TensorFlow (0.7.1) and it worked fine for both cases, so in the worst case you can also try to use TensorFlow as keras backend.

**Comment by naldir** [comment]
The models work well before serialization.
I use `theano 0.8.2`

**Comment by naldir** [comment]
I tried tensorflow but when saving keras_model i have the error `can't pickle module objects`

**Comment by jstypka** [comment]
Sorry with the delay with answering. It's difficult to diagnose the error if I can't reproduce it - from what I understand the error is only with serialization, the main functionality of the software works fine.

For the serialization, I've written actually very little code - the functions that we were discussing do nothing fancy but call external functions (either the `keras` one or the classic `pickle`), you probably noticed that in the code. You're very free to try any other serialization way that you find fit, please let me know how it goes so maybe we can incorporate it into the main system.

From my side, maybe I can try to create a Dockerfile with all the dependencies installed that works fine and anyone can download and run themselves. Do you think it would be helpful for you?

**Comment by naldir** [comment]
I finally managed to get a working loaded model.
Here is how:
I used the latest version of keras theano and tensorflow and saved all things appart.
The keras_model was the part making problems. With the new version there is `model.keras_model.save()` and `keras.models.load_model()` for this.
I used `magpie.utils.save_to_disk()` and `magpie.utils.load_from_disk()` for all the other elements.

**Comment by jstypka** [comment]
Ah, now I see where the problem was. `keras` docs mention that pickle shouldn't be used for serialising the trained model - they don't explain much though. Thanks for the input, I will add appropriate comments to the docs!
