### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by bjlgcxc** [inspirehep/magpie#72]
can somone provides the correct version of numpy，keras ，gensim，scikit-learn and nltk，thank you very much

**Comment by jstypka** [comment]
There's no one correct answer for this, most of the combinations should work. The `numpy`, `scipy` or `nltk` versions should not matter too much. For the other ones, you might want to try:
```
gensim==0.12.4
scikit-learn==0.17
keras==1.0.5
```
Those should work fine. The most important libraries that might have compatibility issues would be `keras` and its underlying backend i.e. `TensorFlow` or `Theano`. You can find detailed instructions how to install them on their websites.

**Comment by bjlgcxc** [comment]
Thank you very much！It works for me

**Comment by jstypka** [comment]
Glad to hear that! Did you install the same versions as I recommended or some other combination also worked?

**Comment by tarvos21** [comment]
Hi, @jstypka, how about now (2017.5.24), what may be the version of these packages for magpie to function normally? I have use all the newest version, but when I `import magpie`, this error happens:
```
from keras.layers.core import Flatten, Dropout, Dense, Merge
ImportError: cannot import name 'Merge'
```

Thanks!

**Comment by jstypka** [comment]
hey @tarvos21, good question!

So Keras recently released a v.2.0 version, that Magpie doesn't support yet. If you install using our `setup.py` file, you should get the [correct version](https://github.com/inspirehep/magpie/blob/master/setup.py#L76). We will migrate Magpie soon to support new Keras, but there should not be significant changes between the two so feel free to use the current one.

**Comment by tarvos21** [comment]
@jstypka thanks, I got it!
