### ISSUE TITLE
Removing Graph model

### ISSUE THREAD

**Issue by devenbhooshan** [inspirehep/magpie#73]
```
from keras.models import Graph
ImportError: cannot import name Graph


```

You should remove the Graph and start using new functional api.
https://github.com/fchollet/keras/issues/2462

**Comment by jstypka** [comment]
Yes, that is necessary to support the new Keras versions. It's not supported at the moment, feel free to open a pull request or you can depend on an older version of Keras e.g. `1.0.0`.

**Comment by devenbhooshan** [comment]
I think `1.0.0` version also doesn't have the Graph?  
We can also use `from .legacy.models import Graph` as a workaround.

**Comment by jstypka** [comment]
Yes, but `legacy.models` is going to disappear in the future versions of Keras if I'm correct, so it's not a long-term solution.

**Comment by devenbhooshan** [comment]
yes. that's why **workaround**
When can we expect this to happen?

**Comment by jstypka** [comment]
How urgently do you need it? I can take a look next week maybe, until then you can switch the import to `legacy`.

**Comment by jstypka** [comment]
I migrated Mapie to new Keras version, so this problem doesn't occur anymore
