### ISSUE TITLE
is test data used for cross validation?

### ISSUE THREAD

**Issue by seunaa** [inspirehep/magpie#74]
How does model.train use the test dataset in the code below?

```python
model.train(path_to_train, labels, test_dir=path_to_test, nb_epochs=5)
```

Does it use it for cross validation or is cross validation done on the training data?

Thanks.

**Comment by jstypka** [comment]
depends on your definition of `cross-validation`, but it basically trains the data on the training set and after each epoch runs the test data to get some kind of an evaluation score.

**Comment by seunaa** [comment]
Thanks.
