### ISSUE TITLE
train_word2vec requires a vocabulary.

### ISSUE THREAD

**Issue by ibigpapa** [inspirehep/magpie#77]
Tried to create a vocabulary by using gensim to create it.  But no input to put the vocabulary in.  Train and Batch Train have them but they  require train_word2vec first. So seems i'm stuck in a circular error.

**Comment by jstypka** [comment]
What do you mean by vocabulary? In the `train` or `batch_train` this parameter means the labels that you want to predict. For `gensim`, you should not need to specify any vocabulary.

**Comment by ibigpapa** [comment]
When i run this below i get the error following the code.

```python
import os

from magpie import MagpieModel

TRAIN_DIR = './train'

def get_labels(directory):
    files = [entry for entry in os.scandir(os.path.realpath(directory)) if entry.is_file() and '.lab' in entry.name]
    content = ''
    for f in files:
        with open(f.path) as fil:
            content += fil.read() + '\n'
    return [l.strip() for l in content.splitlines() if l.strip()]

def train(train_dir, labels, vector_dimensionality=100, epochs=10):
    directory = os.path.realpath(train_dir)
    model = MagpieModel()
    model.train_word2vec(directory, vec_dim=vector_dimensionality)
    model.fit_scaler(directory)
    model.init_word_vectors(directory, vec_dim=vector_dimensionality)
    model.train(directory, labels, nb_epochs=epochs)
    return model

lbls = get_labels(TRAIN_DIR)
model = train(TRAIN_DIR, lbls)
```

``` python
Using TensorFlow backend.
Traceback (most recent call last):
  File "<input>", line 25, in <module>
  File "<input>", line 18, in train
  File "/home/troy_harrison/anaconda3/envs/py3/lib/python3.6/site-packages/magpie-0.2-py3.6.egg/magpie/__init__.py", line 202, in train_word2vec
    self.word2vec_model = train_word2vec(train_dir, vec_dim=vec_dim)
  File "/home/troy_harrison/anaconda3/envs/py3/lib/python3.6/site-packages/magpie-0.2-py3.6.egg/magpie/base/word2vec.py", line 130, in train_word2vec
    window=context,
  File "/home/troy_harrison/anaconda3/envs/py3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 470, in __init__
    self.train(sentences)
  File "/home/troy_harrison/anaconda3/envs/py3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 776, in train
    raise RuntimeError("you must first build vocabulary before training the model")
RuntimeError: you must first build vocabulary before training the model
```

**Comment by jstypka** [comment]
That looks weird, I can't reproduce that. Which `gensim` version do you have?

**Comment by ibigpapa** [comment]
gensim.__version__
'0.13.4.1'

**Comment by jstypka** [comment]
Another thing is that `model.init_word_vectors(directory, vec_dim=vector_dimensionality)` is equivalent to the two lines above, so it's not necessary to run it.

**Comment by jstypka** [comment]
the version looks ok, I'll look at that when I get back home

**Comment by ibigpapa** [comment]
Thanks!

**Comment by jstypka** [comment]
Take a look here:
http://stackoverflow.com/questions/33989826/python-gensim-runtimeerror-you-must-first-build-vocabulary-before-training-th#33991111
or here:
https://github.com/RaRe-Technologies/gensim/issues/541

It seems like the problem might be with your corpus. You can use the `python3-compatibility` branch as well if you want to test out things.

**Comment by bjlgcxc** [comment]
I think you should install ‘python ntlk’ and install its corpus to support word2vec

**Comment by bjlgcxc** [comment]
nltk 3.2.2
numpy 1.12.0
scipy 0.18.1
gensim 0.13.4
sklearn 0.0
keras 1.1.0

this version works

**Comment by ibigpapa** [comment]
Thanks i'll give that a try
