### ISSUE TITLE
Magpie UTF-8 decoding on python 2.7

### ISSUE THREAD

**Issue by NowayIndustries** [inspirehep/magpie#82]
I ran into the following issue when attempting to test magpie:
Using the data in the train folder ([master/data/hep-keywords/data/train](https://github.com/inspirehep/magpie/tree/master/data/hep-keywords/data/train)) I would get the following exception:
**UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 796: ordinal not in range(128)**
it occurs on [line 57 in /magpie/base/document.py in read_sentences](https://github.com/inspirehep/magpie/blob/68fd16987056cdf425c86bc202a017800622624b/magpie/base/document.py#L57) and can be fixed by [forcing UTF-8 decoding in the same file](https://github.com/inspirehep/magpie/blob/68fd16987056cdf425c86bc202a017800622624b/magpie/base/document.py#L32-L34) (by removing the test for python2 and just always decoding).

Thus my assumption is that the Python2 detecting does not function properly.

**My environment is as follows:**
OS: Ubuntu 16.04.2 LTS (xenial)
Kernel: 4.4.0-36-generic
Python: 2.7.12
With the following packages installed in my (brand new) virtualenvironment: 
appdirs==1.4.0, boto==2.46.1, bz2file==0.98, gensim==0.13.4.1, h5py==2.6.0, Keras==1.1.1  , magpie==0.2, nltk==3.2.2, numpy==1.12.0, packaging==16.8, pkg-resources==0.0.0, pyparsing==2.1.10, PyYAML==3.12, requests==2.13.0, scikit-learn==0.18.1, scipy==0.18.1, six==1.10.0, smart-open==1.4.0, Theano==0.8.2

**My install commands are as follows:**
pip install git+https://github.com/inspirehep/magpie.git
pip install theano

If I manually 'fix' this issue by always decoding the MagPie model can be properly trained and used (with the same data).

**Comment by NowayIndustries** [comment]
**Full stacktrace:**
```
Using Theano backend.
Traceback (most recent call last):
  File "magpie-train.py", line 14, in <module>
    model.init_word_vectors(training_dir, vec_dim=vecdim)
  File "/home/sn/.virtualenvs/magpie-bugfix/local/lib/python2.7/site-packages/magpie/__init__.py", line 188, in init_word_vectors
    self.train_word2vec(train_dir, vec_dim=vec_dim)
  File "/home/sn/.virtualenvs/magpie-bugfix/local/lib/python2.7/site-packages/magpie/__init__.py", line 202, in train_word2vec
    self.word2vec_model = train_word2vec(train_dir, vec_dim=vec_dim)
  File "/home/sn/.virtualenvs/magpie-bugfix/local/lib/python2.7/site-packages/magpie/base/word2vec.py", line 131, in train_word2vec
    window=context,
  File "/home/sn/.virtualenvs/magpie-bugfix/local/lib/python2.7/site-packages/gensim/models/word2vec.py", line 469, in __init__
    self.build_vocab(sentences, trim_rule=trim_rule)
  File "/home/sn/.virtualenvs/magpie-bugfix/local/lib/python2.7/site-packages/gensim/models/word2vec.py", line 533, in build_vocab
    self.scan_vocab(sentences, progress_per=progress_per, trim_rule=trim_rule)  # initial survey
  File "/home/sn/.virtualenvs/magpie-bugfix/local/lib/python2.7/site-packages/gensim/models/word2vec.py", line 545, in scan_vocab
    for sentence_no, sentence in enumerate(sentences):
  File "/home/sn/.virtualenvs/magpie-bugfix/local/lib/python2.7/site-packages/magpie/base/word2vec.py", line 116, in __iter__
    for sentence in d.read_sentences():
  File "/home/sn/.virtualenvs/magpie-bugfix/local/lib/python2.7/site-packages/magpie/base/document.py", line 57, in read_sentences
    lines = self.text.split('\n')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 796: ordinal not in range(128)
```
when running magpie-train.py:
```
from magpie import MagpieModel
from magpie import utils
import os.path

model = MagpieModel()
training_dir = 'train'
test_dir = '' #Optional for training.
#labels = ['label1', 'label2', 'label3']
labels = ['potential: chemical', 'Polyakov loop: correlation function', 'gauge field theory: SU(3)', 'mean field approximation', 'lattice field theory', 'critical phenomena', 'scalar particle', 'heavy quark', 'lattice', 'numerical calculations', 'effective action', 'Higgs model: nonabelian', 'field theory: scalar']
saving_dir = 'saved'
vecdim = 100
epochs = 30

model.init_word_vectors(training_dir, vec_dim=vecdim)

model.train(training_dir, labels, test_dir=test_dir, nb_epochs=epochs)
#Probably need batch_train() instead of train because of memory limitations.

#saving after training:
#model.init_word_vectors(os.path.join(os.getcwd(), saving_dir, 'wordvectors.magpie'), vec_dim=vecdim)
utils.save_to_disk(os.path.join(os.getcwd(), saving_dir, 'word2vec-model.magpie'), model.word2vec_model)
utils.save_to_disk(os.path.join(os.getcwd(), saving_dir, 'scaler.magpie'), model.scaler, overwrite=True)
model.keras_model.save(os.path.join(os.getcwd(), saving_dir, 'keras-model.magpie'))

```
labels are from 1037765.lab, which is the file I ran against the trained model to get an example of output.

**Comment by jstypka** [comment]
Hey @NowayIndustries ! Thanks a lot for submitting the issue, you might be right - there might be a bug there.

Do you mean that the [Python2 compatibility block](https://github.com/inspirehep/magpie/blob/68fd16987056cdf425c86bc202a017800622624b/magpie/base/document.py#L32-L34) is not being run for your case and if you run it manually then it works? What is the type of `self.text` then? Could you add some prints so we can see what's going on?

For example:
```
    with open(filepath, 'r') as f:
        self.text = f.read()
        print(type(self.text))

        # Python 2 compatibility
        if type(self.text) != str:
            print("Python2 compatibility block is being run")
            self.text = self.text.decode('utf-8')
```

**Comment by NowayIndustries** [comment]
Hello @jstypka thanks for the fast response!

> Do you mean that the Python2 compatibility block is not being run for your case and if you run it manually then it works?
Yes, if I alter the document.py to have:
```
with open(filepath, 'r') as f:
    self.text = f.read()

    # Python 2 compatibility
    #if type(self.text) != str:
    self.text = self.text.decode('utf-8')
```
magpie will succesfully train a model (and can be used to predict labels using that model).

>  What is the type of self.text then? Could you add some prints so we can see what's going on?

With the prints added to document.py:
```
Using Theano backend.
<type 'str'>
<type 'str'>
<type 'str'>
<type 'str'>
Traceback (most recent call last):
  File "magpie-train.py", line 14, in <module>
    model.init_word_vectors(training_dir, vec_dim=vecdim)
  File "/home/sn/.virtualenvs/magpie-bugfix/local/lib/python2.7/site-packages/magpie/__init__.py", line 188, in init_word_vectors
    self.train_word2vec(train_dir, vec_dim=vec_dim)
  File "/home/sn/.virtualenvs/magpie-bugfix/local/lib/python2.7/site-packages/magpie/__init__.py", line 202, in train_word2vec
    self.word2vec_model = train_word2vec(train_dir, vec_dim=vec_dim)
  File "/home/sn/.virtualenvs/magpie-bugfix/local/lib/python2.7/site-packages/magpie/base/word2vec.py", line 131, in train_word2vec
    window=context,
  File "/home/sn/.virtualenvs/magpie-bugfix/local/lib/python2.7/site-packages/gensim/models/word2vec.py", line 469, in __init__
    self.build_vocab(sentences, trim_rule=trim_rule)
  File "/home/sn/.virtualenvs/magpie-bugfix/local/lib/python2.7/site-packages/gensim/models/word2vec.py", line 533, in build_vocab
    self.scan_vocab(sentences, progress_per=progress_per, trim_rule=trim_rule)  # initial survey
  File "/home/sn/.virtualenvs/magpie-bugfix/local/lib/python2.7/site-packages/gensim/models/word2vec.py", line 545, in scan_vocab
    for sentence_no, sentence in enumerate(sentences):
  File "/home/sn/.virtualenvs/magpie-bugfix/local/lib/python2.7/site-packages/magpie/base/word2vec.py", line 116, in __iter__
    for sentence in d.read_sentences():
  File "/home/sn/.virtualenvs/magpie-bugfix/local/lib/python2.7/site-packages/magpie/base/document.py", line 58, in read_sentences
    lines = self.text.split('\n')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 796: ordinal not in range(128)
```
So it appears that somehow the assumption that self.text would not be a str in python 2 is untrue, perhaps this was changed in an python update (or the logic is the wrong way around)? The python2 compatibility check was introduced in #80, before that everything would always be decoded. 

Again thank you for the swift response.

**Comment by jstypka** [comment]
hmmm, I think it's a bug from my side. It should work for Python3, but the Python2 bypass seems hacky. I'll look up for better ways to do it (probably with `six`) and will try to fix it this evening :)

**Comment by jstypka** [comment]
by the way, maybe @jacquerie knows a smart way of loading utf-8 encoded files in a consistent way against Python2 and Python3?

**Comment by NowayIndustries** [comment]
Sounds good to me!
I will be able to test any fixes tomorrow, should you need me.
(Maybe I'll even migrate to python3 once the current pull request is merged)

**Comment by jstypka** [comment]
hey @NowayIndustries , I added a fix in the PR #83. Could you use test whether it works for you before merging? You can find the new code on the (very descriptive) branch `fix-file-reading-in-py2`

**Comment by NowayIndustries** [comment]
Hello @jstypka 
Everything seems to be working fine with PR #83,
after installing with 
`pip install https://github.com/inspirehep/magpie.git@fix-file-reading-inpy2`
into another new virtualenv (with the other things installed aswell)
and verifying that document.py has the new io.open I reran my training and testing scripts,
both are functioning perfectly.

Thank you for the support

**Comment by jstypka** [comment]
cool, we'll try to merge the PR then!
