### ISSUE TITLE
Adding additional columns to the text as input to train the model ?

### ISSUE THREAD

**Issue by degorsse** [inspirehep/magpie#87]
Hello,

One (silly?) question:
Do you know if we could add new columns from the initial training set file ?

We would like to add some text analytics (integer & float) to every text we input to train the multi class model.
 
Thanks for your help,
Best regards,
Matthieu

**Comment by jstypka** [comment]
Hmmmm, not in any easy way I'm afraid 😕  You could in theory try to experiment with expressing your metrics as vectors and adding them to the representation just before you feed the text to the network. But that seems quite complicated and I'm not sure if it wouldn't decrease the performance.

**Comment by degorsse** [comment]
Thanks for your help. Seems complicated. We will try to find an intelligent alternative (like replacing the figures by some more text ?!).
One last question: Do you know other scripts that would be able to build a neural network for text multi-classification ?

**Comment by jstypka** [comment]
I don't know of any existing NN frameworks for this. It should not be complicated to do with a linear model though like the one I sent you a couple of weeks ago.
