### ISSUE TITLE
Minor Correction in README.md

### ISSUE THREAD

**Issue by puevigreven** [inspirehep/magpie#93]
README.md has line `model.predict_from_file('data/hep-categories/1002413.txt')` which is incorrect and it gives error `NameError: name 'model' is not defined.` 
The line should be `magpie.predict_from_text('Stephen Hawking studies black holes')`

**Comment by puevigreven** [comment]
Please check the PR at: https://github.com/inspirehep/magpie/pull/94

**Comment by jstypka** [comment]
Right, thanks for spotting it!
